- name: install fail2ban package
  package: 
    name: "{{ fail2ban_package }}" 
    state: latest

- name: place ssh jail config
  copy: src="sshd_jail.conf" dest="/etc/fail2ban/jail.d/sshd_jail.conf" owner=root group=root mode=644

- name: Ensure /var/run/fail2ban exists
  file:
    path: /var/run/fail2ban
    ensure: directory
    owner: root
    group: root

- name: enable and start fail2ban service
  service: name=fail2ban state=started enabled=yes
