---

- name: Check if python-dnf is installed (bare-bones way)
  shell: rpm -qa | grep python2-dnf
  ignore_errors: yes
  register: dnf_check
  when: ansible_distribution == "Fedora"

- name: Install python2-dnf, required by all other installation tasks
  become: yes
  shell: dnf install python2-dnf -y
  when: dnf_check|failed and ansible_distribution == "Fedora"

- name: Install global/nice-to-have dependencies
  package:
    name: "{{ item }}"
  with_items: "{{ global_packages }}"